### PR TITLE
Use tmp table in static insert overwrite

### LINKED ISSUE #427: [CT-1646] [CT-1170] [Bug] Insert overwrite incremental models not using dbt_tmp table
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run an incremental table update using the `insert_overwrite` strategy, the created `dbt_tmp` table isn't used to update the destination table. Instead, the model code is rerun from scratch. 

### Expected Behavior

Rather than rerunning the model code from scratch, I expected the destination table update to use the created `dbt_tmp` table.

### Steps To Reproduce

The specific model is called `gross_and_net_churn.sql`. I'll exclude the main body of the model for brevity (I've confirmed this is happening with multiple models), but the config params are:

```
{% set partitions_to_replace = days_between_two_dates(var("subscriptions_crawler_start_date"), var("subscriptions_crawler_end_date")) %}

{{
    config(
        materialized="incremental",
        incremental_strategy="insert_overwrite",
        partition_by = {"field": "report_date", "data_type": "timestamp", "granularity": "day"},
        partitions = partitions_to_replace,
        cluster_by = ["report_date", "client"]
    )
}}
```

On dbt CLI, I ran:

```
dbt run --select models/subscription_retention/gross_and_net_churn.sql  
```

I then looked at which queries got executed in the [BigQuery console](https://console.cloud.google.com/bigquery).

The first query run created the `dbt_tmp` table:

```
/* {"app": "dbt", "dbt_version": "1.2.1", "profile_name": "data_science", "target_name": "dev", "node_id": "model.subscriptions.gross_and_net_churn"} */

  create or replace table `duolingo-data-science`.`dbt_naveen`.`gross_and_net_churn__dbt_tmp`
  partition by timestamp_trunc(report_date, day)
  cluster by report_date, client
  OPTIONS(
      description="""""",
    
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 hour)
    )
  as (

[Main body of model]    

  );
```

The second query run did the actual update:

```
/* {"app": "dbt", "dbt_version": "1.2.1", "profile_name": "data_science", "target_name": "dev", "node_id": "model.subscriptions.gross_and_net_churn"} */

    merge into `duolingo-data-science`.`dbt_naveen`.`gross_and_net_churn` as DBT_INTERNAL_DEST
        using (

[Main body of model]          

        ) as DBT_INTERNAL_SOURCE
        on FALSE

    when not matched by source
         and timestamp_trunc(DBT_INTERNAL_DEST.report_date, day) in (
              '2022-08-13', '2022-08-14', '2022-08-15', '2022-08-16', '2022-08-17', '2022-08-18', '2022-08-19', '2022-08-20', '2022-08-21', '2022-08-22', '2022-08-23', '2022-08-24', '2022-08-25', '2022-08-26', '2022-08-27', '2022-08-28', '2022-08-29', '2022-08-30', '2022-08-31', '2022-09-01', '2022-09-02', '2022-09-03', '2022-09-04', '2022-09-05', '2022-09-06', '2022-09-07', '2022-09-08', '2022-09-09', '2022-09-10', '2022-09-11', '2022-09-12'
          ) 
        then delete

    when not matched then insert
        (`report_date`, `client`, `subscription_type`, `is_new_years`, `subscription_tier`, `country_code`, `active_subscriptions`, `expirations`, `expirations_and_winbacks`, `winbacks`)
    values
        (`report_date`, `client`, `subscription_type`, `is_new_years`, `subscription_tier`, `country_code`, `active_subscriptions`, `expirations`, `expirations_and_winbacks`, `winbacks`)
```

Just as the [documentation](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#merge-behavior-incremental-models) suggests, I would've expected the second query to use the `gross_and_net_churn__dbt_tmp` table, rather than rerunning the entire main body of the model. Or in other words, it seems like the second query should be:

```
using (gross_and_net_churn__dbt_tmp)
```

rather than 

```
using ([Main body of model])
```

As far as I can tell, the created `gross_and_net_churn__dbt_tmp` table isn't used at all, anywhere.

So the output is correct, but dbt is seemingly unnecessarily running the same query twice, leading to a performance hit. 

### Relevant log output

_No response_

### Environment

```markdown
- OS: Monterey 12.4
- Python: 3.8.0
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I've seen this happen with a couple models. In one example, the first query took 17 minutes and the second query took 23 minutes.

### LINKED ISSUE #556: [CT-2170] Temporary table not deleted after dbt job finishes running
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Ok, I'm running a model that goes as follows:

```
{{
    config(
        materialized = 'incremental',
        unique_key = 'id',
        on_schema_change = 'sync_all_columns',
        partition_by = {
          'field': 'created_date',
          'data_type': 'datetime',
          'granularity': 'day'
        },
        require_partition_filter = false,
        incremental_strategy = 'insert_overwrite',
        partitions = ["'2023-02-01'", "'2023-02-02'"]
    )
}}

  SELECT
    *
  FROM
    {{ source(source_schema,source_table) }}
{% if is_incremental() %}
  -- this filter will only be applied on an incremental run
    WHERE date(created_date) in ('2023-02-01', '2023-02-02')
      and updated_date >= '2023-02-20 19:00:01.873000'
{% endif %}
```

Since I am providing partitions, it is using static insert_overwrite method.

It generates a query which goes like this:

```
create or replace table `project`.`target_dataset`.`table_name__dbt_tmp`
    partition by datetime_trunc(created_date, day)
    
    OPTIONS(
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 hour)
    )
    as (

-- Use the `ref` function to select from other models

  SELECT
    *
  FROM
    `project`.`source_dataset`.`table_name`
  -- this filter will only be applied on an incremental run
  WHERE date(created_date) in ('2023-02-01', '2023-02-02')
      and updated_date >= '2023-02-20 19:00:01.873000'

    );


merge into `project`.`target_dataset`.`table_name` as DBT_INTERNAL_DEST
        using (

-- Use the `ref` function to select from other models

  SELECT
    *
  FROM
    `project`.`source_dataset`.`table_name`
  -- this filter will only be applied on an incremental run
  WHERE date(created_date) in ('2023-02-01', '2023-02-02')
      and updated_date >= '2023-02-20 19:00:01.873000'
) as DBT_INTERNAL_SOURCE
        on FALSE

    when not matched by source
         and datetime(datetime_trunc(DBT_INTERNAL_DEST.created_date, day)) in (
              '2023-02-01', '2023-02-02'
          )
        then delete

    when not matched then insert
        (`id`, `created_date`, `updated_date`, `status`)
    values
        (`id`, `created_date`, `updated_date`, `status`)
```

As you can see from the above query, there is no `drop table if exists` query running to delete the temporary table. Granted, the table is set to expire in 12 hours, but still, this does not occur when using dynamic insert overwrite & leads to clutter in the target dataset.

The macro for dynamic insert overwrite which is `bq_dynamic_insert_overwrite_sql` does have `drop table if exists {{ tmp_relation }}` in the code which deletes the temporary table.

But the macro for static insert overwrite which is `bq_static_insert_overwrite_sql` doesn't.

### Expected Behavior

The macro for static insert_overwrite should delete the temporary table at the end. Simply adding `drop table if exists {{ tmp_relation }}` in macro  `bq_static_insert_overwrite_sql` would resolve the issue.

### Steps To Reproduce

Run a model with above parameters as described or any model which uses static insert_overwrite method by passing the `partitions` parameter in config.

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt-core: 1.4.1
- dbt-bigquery: 1.4.1
```

### Additional Context

Ready to raise PR for the same. Just need confirmation from someone to proceed.

### PR DESCRIPTION
**Pull request by github-christophe-oudar**
Resolves #427
Resolves #556

### Description

As described in #427, static insert overwrite, when involving `on_schema_change != 'ignore'` would create a temp table to check for a schema change anyway.
It fixes as well:
- In case, `on_schema_change = 'ignore'` with dynamic insert overwrite where the SQL header would not be added
- In case, we would have static insert overwrite with `on_schema_change != 'ignore'` where the temp table would not be deleted

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

File: dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql [hunk 1]
```diff
@@ -1,5 +1,5 @@
 {% macro bq_generate_incremental_insert_overwrite_build_sql(
-    tmp_relation, target_relation, sql, unique_key, partition_by, partitions, dest_columns, on_schema_change, copy_partitions
+    tmp_relation, target_relation, sql, unique_key, partition_by, partitions, dest_columns, tmp_relation_exists, copy_partitions
```
Comment (github-christophe-oudar) [inline dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql:2]: [Align the parameter naming on the call site variable name](https://github.com/Kayrnt/dbt-bigquery/blob/5b691e3b848cda102ba8f0688a4ab850475bf3c2/dbt/include/bigquery/macros/materializations/incremental.sql#L48)

**Comment by github-christophe-oudar** [comment]
I think it should work as intended, should we move forward on that one for 1.6 release?

**Comment by mikealfare** [comment]
@Kayrnt We just merged in a bunch of smaller dependabot type changes. Now that that's all done, do you mind updating your branch?

**Comment by Kayrnt** [comment]
I just rebased, let's see if it passes the tests

**Comment by mikealfare** [comment]
@Kayrnt Don't worry about the one failed test this last CI run, we see that fail sporadically (flaky test) and we're working on fixing that.

File: dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql [hunk 2]
```diff
@@ -69,13 +75,19 @@
...
-         in the "dynamic" case, we save the model SQL result as a temp table first, wherein the
+         in the "temporary table exists" case, we save the model SQL result as a temp table first, wherein the
          sql_header is included by the create_table_as macro.
       #}
-      {{ get_insert_overwrite_merge_sql(target_relation, source_sql, dest_columns, [predicate], include_sql_header=true) }}
+      -- 1. run the merge statement
+      {{ get_insert_overwrite_merge_sql(target_relation, source_sql, dest_columns, [predicate], include_sql_header = not tmp_relation_exists) }}
+
+      {%- if tmp_relation_exists -%}
+      -- 2. clean up the temp table
```
Comment (colin-rogers-dbt) [inline dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql:88]: I think we need to add a `;`

**Comment by colin-rogers-dbt** [comment]
Local testing shows that runs with `--full-refresh` succeeds as expected but on rerun we get an error: `Syntax error: Expected end of input but got keyword DROP at [27:7]`

File: dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql (hunk 2 above)
Comment (github-christophe-oudar) [reply dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql:88]: After the drop table? Sure it's not a bad idea if there's anything that follows that statement.

File: dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql [hunk 3]
```diff
@@ -57,10 +57,16 @@
 
       {%- set source_sql -%}
         (
-          {%- if partition_by.time_ingestion_partitioning -%}
-          {{ wrap_with_time_ingestion_partitioning_sql(partition_by, sql, True) }}
+          {%- if tmp_relation_exists -%}
```
[the remark this answers is not in the document]
Comment (Kayrnt) [reply dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql:60]: I don't mind, if you feel like it's more readable 👍

File: dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql (hunk 2 above)
Comment (colin-rogers-dbt) [reply dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql:88]: before the drop table otherwise BQ doesn't realize these are separate statements, hence error: https://github.com/dbt-labs/dbt-bigquery/pull/630#issuecomment-1632975065

File: .changes/unreleased/Fixes-20230325-204352.yaml [hunk 4]
```diff
@@ -0,0 +1,6 @@
+kind: Fixes
+body: Use tmp table in static insert overwrite to avoid computing the SQL twice
+time: 2023-03-25T20:43:52.830135+01:00
+custom:
+  Author: Kayrnt
+  Issue: "427"
```
Comment (dbeatty10) [inline .changes/unreleased/Fixes-20230325-204352.yaml:6]: Since this is closing two different issues:
```suggestion
  Issue: 427 556
```

**Comment by colin-rogers-dbt** [comment]
Local testing successful and it looks like we're now using the temp table as expected.

**Comment by colin-rogers-dbt** [comment]
Last request: can we add a test fixture that covers this here: https://github.com/dbt-labs/dbt-bigquery/blob/main/tests/functional/adapter/incremental/test_incremental_strategies.py

Suggested fixture:
```
{% set partitions_to_replace = [
  "date_sub(current_date, interval 1 day)",
  "date_sub(current_date, interval 2 day)"
] %}

{{
    config(
        materialized="incremental",
        incremental_strategy="insert_overwrite",
        cluster_by="id",
        partition_by={
            "field": "date_time",
            "data_type": "datetime",
            "granularity": "day"
        },
        partitions=partitions_to_replace,
        on_schema_change="sync_all_columns"
    )
}}


with data as (

    {% if not is_incremental() %}

        select 1 as id, cast('2020-01-01' as datetime) as date_time union all
        select 2 as id, cast('2020-01-01' as datetime) as date_time union all
        select 3 as id, cast('2020-01-01' as datetime) as date_time union all
        select 4 as id, cast('2020-01-01' as datetime) as date_time

    {% else %}

        -- we want to overwrite the 4 records in the 2020-01-01 partition
        -- with the 2 records below, but add two more in the 2020-01-02 partition
        select 10 as id, cast('2020-01-01' as datetime) as date_time union all
        select 20 as id, cast('2020-01-01' as datetime) as date_time union all
        select 30 as id, cast('2020-01-02' as datetime) as date_time union all
        select 40 as id, cast('2020-01-02' as datetime) as date_time

    {% endif %}

)

select * from data
```

**Review by colin-rogers-dbt — APPROVED** [review]

**Comment by colin-rogers-dbt** [comment]
if we can do one more update I can merge this

**Comment by github-christophe-oudar** [comment]
Done 👍

**Comment by McKnight-42** [comment]
@cla-bot check

**Comment by Kayrnt** [comment]
@McKnight-42 @colin-rogers-dbt I rebased with my "cla:yes" account (my personal one) so that it should be OK.
I initially rebased earlier today because with my other account as I was logged in on it.
