### PR TITLE
Fix UDF usage with time ingestion

### LINKED ISSUE #684: [ADAP-499] [Bug] UDF don't work with `time_ingestion_partitioning`
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Any model using `time_ingestion_partitioning` and an UDF is failing

### Expected Behavior

The model should work as intended like without `time_ingestion_partitioning`

### Steps To Reproduce

Using dbt 1.4+ (for the time ingestion support)
```
{{
    config(
        materialized="incremental",
        incremental_strategy='insert_overwrite',
        cluster_by="id",
        partition_by={
            "field": "date_time",
            "data_type": "datetime",
            "time_ingestion_partitioning": true
        },
        require_partition_filter=true
    )
}}

{%- call set_sql_header(config) %}
 CREATE TEMP FUNCTION asDateTime(date STRING) AS (
   cast(date as datetime)
 );
{%- endcall %}

with data as (

    {% if not is_incremental() %}

        select 1 as id, asDateTime('2020-01-01') as date_time union all
        select 2 as id, asDateTime('2020-01-01') as date_time union all
        select 3 as id, asDateTime('2020-01-01') as date_time union all
        select 4 as id, asDateTime('2020-01-01') as date_time

    {% else %}

        -- we want to overwrite the 4 records in the 2020-01-01 partition
        -- with the 2 records below, but add two more in the 2020-01-02 partition
        select 10 as id, asDateTime('2020-01-01') as date_time union all
        select 20 as id, asDateTime('2020-01-01') as date_time union all
        select 30 as id, cast('2020-01-02' as datetime) as date_time union all
        select 40 as id, cast('2020-01-02' as datetime) as date_time

    {% endif %}

)

select * from data

{% if is_incremental() %}
where date_time > '2020-01-01'
{% endif %}
```

### Relevant log output

_No response_

### Environment

```markdown
- OS: MacOs
- Python: 3.11.3
- dbt-core: 1.5.0-b5
- dbt-bigquery: 1.5.0-b5
```

### Additional Context

Current workaround (same as the fix)

Add a macro override in your dbt project
```
{#
    Temporary fix for UDF usage in dbt with time ingestion tables
#}
{% macro get_columns_with_types_in_query_sql(select_sql) %}
  {% set sql %}
    {%- set sql_header = config.get('sql_header', none) -%}
    {{ sql_header if sql_header is not none }}
    select * from (
      {{ select_sql }}
    ) as __dbt_sbq
    where false
    limit 0
  {% endset %}
  {{ return(adapter.get_columns_in_select_sql(sql)) }}
{% endmacro %}

{% macro bq_insert_into_ingestion_time_partitioned_table_sql(target_relation, sql) -%}
  {%- set sql_header = config.get('sql_header', none) -%}
  {{ sql_header if sql_header is not none }}
  {%- set raw_partition_by = config.get('partition_by', none) -%}
  {%- set partition_by = adapter.parse_partition_by(raw_partition_by) -%}
  {% set dest_columns = adapter.get_columns_in_relation(target_relation) %}
  {%- set dest_columns_csv = get_quoted_csv(dest_columns | map(attribute="name")) -%}

  insert into {{ target_relation }} ({{ partition_by.insertable_time_partitioning_field() }}, {{ dest_columns_csv }})
    {{ wrap_with_time_ingestion_partitioning_sql(partition_by, sql, False) }}

{%- endmacro -%}
```

### PR DESCRIPTION
**Pull request by Kayrnt**
resolves #684

### Description

When including UDF with BigQuery, those needs to be wrapped in the `sql_header` as the syntax prevents them to be inlined anywhere in the code. Therefore, like [default implementation](https://github.com/dbt-labs/dbt-core/blob/d2f963e20ea945355db57ff3d34a318429a8bf1e/core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql#L21), we have to include them in the materialization specific macros.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

File: dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql [hunk 1]
```diff
@@ -36,6 +38,8 @@
 
 {% macro get_columns_with_types_in_query_sql(select_sql) %}
   {% set sql %}
+    {%- set sql_header = config.get('sql_header', none) -%}
+    {{ sql_header if sql_header is not none }}
```
Comment (VersusFacit) [inline dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql:42]: nit: pretty sure this is actually redundant since Jinja renders None as ... well nothing

File: dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql [hunk 2]
```diff
@@ -24,6 +24,8 @@
 {%- endmacro -%}
 
 {% macro bq_insert_into_ingestion_time_partitioned_table_sql(target_relation, sql) -%}
+  {%- set sql_header = config.get('sql_header', none) -%}
+  {{ sql_header if sql_header is not none }}
```
Comment (VersusFacit) [inline dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql:28]:
```suggestion
  {{ sql_header }}
```

File: dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql (hunk 1 above)
Comment (VersusFacit) [inline dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql:42]:
```suggestion
    {{ sql_header }}
```
nit: pretty sure this if guard is actually redundant since Jinja renders None as ... well nothing

**Review by VersusFacit — COMMENTED** [review]
Looking good! Tiny comments to explore rq; I can merge after

**Comment by Kayrnt** [comment]
Indeed that one was easy!
I've still to figure out the regressions on https://github.com/dbt-labs/dbt-bigquery/pull/630

**Comment by github-christophe-oudar** [comment]
@VersusFacit I reverted the suggested change as it wasn't working as intended (it was printing "None")

**Comment by VersusFacit** [comment]
Oh, well then I guess i'll have to recommend empty strings in the future – thanks for letting me know about that. I feel like I'm always learning new Jinja hacks despite the Python underneath it

**Comment by github-christophe-oudar** [comment]
Yes that could be an option but I think we can stick to that syntax for the time being, it's consistent with other references.

**Comment by VersusFacit** [comment]
Yeah later when this comes back as green I'll merge up – thanks for your work here

**Review by VersusFacit — APPROVED** [review]
