### PR TITLE
ADAP-972: Fix issue where materialized views were being mapped as tables in catalog queries

### LINKED ISSUE #995: [ADAP-972] [Bug] Materialized views show up as tables in catalog queries
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Materialized views show up as tables in catalog queries.

### Expected Behavior

Materialized views should show up as materialized views in catalog queries.

### Steps To Reproduce

1. Create a materialized view
2. Run `docs generate`
3. Notice that the type for the materialized view is "table"

For more details, refer to: https://github.com/dbt-labs/dbt-core/issues/8864

### Relevant log output

_No response_

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mikealfare**
resolves #995, dbt-labs/dbt-core#8864

### Problem

Materialized views were being mapped as tables in catalog queries.

### Solution

- write a test demonstrating the issue
- update the catalog query to return the correct type

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt/include/bigquery/macros/catalog.sql [hunk 1]
```diff
@@ -7,30 +7,42 @@
...
+                when materialized_views.table_id is not null then 'materialized view'
+                when tables.type = 1 then 'table'
+                when tables.type = 2 then 'view'
                 else 'external'
             end as table_type,
 
-            REGEXP_CONTAINS(table_id, '^.+[0-9]{8}$') and coalesce(type, 0) = 1 as is_date_shard,
-            REGEXP_EXTRACT(table_id, '^(.+)[0-9]{8}$') as shard_base_name,
-            REGEXP_EXTRACT(table_id, '^.+([0-9]{8})$') as shard_name
+            REGEXP_CONTAINS(tables.table_id, '^.+[0-9]{8}$') and coalesce(type, 0) = 1 as is_date_shard,
```
Comment (VersusFacit) [inline dbt/include/bigquery/macros/catalog.sql:34]: These regexes make me uncomfortable. Is there any way to pull them out as vars or something so we can at least document them a la C macros? If nothing else, it might be nice to know those that should be the same, do in fact stay the same

File: tests/functional/adapter/catalog_tests/test_relation_types.py [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+
+class TestCatalogRelationTypes:
+    @pytest.fixture(scope="class", autouse=True)
+    def seeds(self):
+        return {"my_seed.csv": files.MY_SEED}
+
+    @pytest.fixture(scope="class", autouse=True)
+    def models(self):
+        yield {
```
Comment (VersusFacit) [inline tests/functional/adapter/catalog_tests/test_relation_types.py:15]: What's up with `yield` over return.

Also, really like the flow this test. Points for aesthetic.

File: dbt/include/bigquery/macros/catalog.sql [hunk 3]
```diff
@@ -7,30 +7,42 @@
...
+            concat(tables.project_id, '.', tables.dataset_id, '.', tables.table_id) as relation_id,
 
-            row_count,
-            size_bytes as size_bytes,
+            tables.row_count,
+            tables.size_bytes as size_bytes,
             case
-                when type = 1 then 'table'
-                when type = 2 then 'view'
+                when materialized_views.table_id is not null then 'materialized view'
```
Comment (VersusFacit) [inline dbt/include/bigquery/macros/catalog.sql:28]: given that the config block, should this be `materialized_view` instead of here with the space. A nit only. Just thinking about consistency of output.

File: dbt/include/bigquery/macros/catalog.sql [hunk 4]
```diff
@@ -7,30 +7,42 @@
...
-            REGEXP_CONTAINS(table_id, '^.+[0-9]{8}$') and coalesce(type, 0) = 1 as is_date_shard,
-            REGEXP_EXTRACT(table_id, '^(.+)[0-9]{8}$') as shard_base_name,
-            REGEXP_EXTRACT(table_id, '^.+([0-9]{8})$') as shard_name
+            REGEXP_CONTAINS(tables.table_id, '^.+[0-9]{8}$') and coalesce(type, 0) = 1 as is_date_shard,
+            REGEXP_EXTRACT(tables.table_id, '^(.+)[0-9]{8}$') as shard_base_name,
+            REGEXP_EXTRACT(tables.table_id, '^.+([0-9]{8})$') as shard_name
 
-        from {{ information_schema.replace(information_schema_view='__TABLES__') }}
+        from {{ information_schema.replace(information_schema_view='__TABLES__') }} tables
+        left join materialized_views
```
Comment (VersusFacit) [inline dbt/include/bigquery/macros/catalog.sql:39]: I honestly don't know the answer here: Why is `left join` the right answer? Is your thinking that some tables will not have a materialized view entry to match it (i.e. they aren't materialized views even though we see them as tables).

**Review by VersusFacit — COMMENTED** [review]
Several nits around Jinja implementation. 

Logic seems good since you're just adding on an extra information schema call and differentiating that set from the existing set. 

Great test with exhaustive but clear use cases. That `yield` for the docs fixture is magical

File: dbt/include/bigquery/macros/catalog.sql (hunk 1 above)
Comment (mikealfare) [reply dbt/include/bigquery/macros/catalog.sql:34]: They were already there. Those lines show up because I suffixed the column name with `tables.`. Perhaps we should revisit them (I share your concern), but that would be outside of the scope of this PR.

File: tests/functional/adapter/catalog_tests/test_relation_types.py (hunk 2 above)
Comment (mikealfare) [reply tests/functional/adapter/catalog_tests/test_relation_types.py:15]: I suppose it doesn't matter here, as nothing happens after the `yield` in the fixture. The convention for a pytest fixture is:

```python
@pytest.fixture()
def my_cool_fixture(self):
    # do some setup pre-test
    yield some_value_you_want
    # do some teardown post-test
```

When the fixture simply returns a value, this can be simplified to:

```python
@pytest.fixture()
def my_cool_fixture(self):
    return some_value_you_want
```

I use `yield` out of habit of writing a pytest fixture, but both are valid.

File: dbt/include/bigquery/macros/catalog.sql (hunk 3 above)
Comment (mikealfare) [reply dbt/include/bigquery/macros/catalog.sql:28]: I thought about this in general for the three related PRs. It looks like we always return it with a space, but we return all caps for some adapters, all lowercase for others, and sometimes we return `"BASE TABLE"` whereas others return `"table"`. I feel like all of these should be standardized (probably to the `RelationType` enum), but I don't know if Cloud is depending on this list of values somehow. Given all of that, `'materialized view'` seemed the most consistent for now.

File: dbt/include/bigquery/macros/catalog.sql (hunk 4 above)
Comment (mikealfare) [reply dbt/include/bigquery/macros/catalog.sql:39]: That's correct. I'm left joining just to see if the record I'm looking at belongs to a materialized view. We need the types for all relations, not just materialized views; if we inner join, we'll drop all of the tables and views.

File: dbt/include/bigquery/macros/catalog.sql (hunk 1 above)
Comment (VersusFacit) [reply dbt/include/bigquery/macros/catalog.sql:34]: I can get behind that. They are clearing working right now. I just find the whole thing uncomfy as coding practice. However, since it's just a simple/intentional copy-paste job, I can get behind that.

File: tests/functional/adapter/catalog_tests/test_relation_types.py (hunk 2 above)
Comment (VersusFacit) [reply tests/functional/adapter/catalog_tests/test_relation_types.py:15]: Wouldn't have guessed they were functionally equivalent. Weird then that we are using return in several places where yield does the job (and is more idiomatic). Oh well -- getting to know our tools! :)

File: dbt/include/bigquery/macros/catalog.sql (hunk 3 above)
Comment (VersusFacit) [reply dbt/include/bigquery/macros/catalog.sql:28]: you've clearly weighed the options which is what I was wondering most. I agree standardization is kind of a separate, high-level thing we'll need to address some day if the need presents itself. For now, I can live with the current state of affairs (even if from the outside I'd be asking 'wat')

**Review by VersusFacit — APPROVED** [review]
